### ISSUE TITLE
Darstellung Anführungszeichen im Aufgabennamen

### ISSUE THREAD

**Issue by LK42** [JonaRL/itask#1]
Im Namen einer Aufgabe befinden sich zwei obere Anführungszeichen (Englisch), die in ITask jedoch als `&quot;` angezeigt werden. 
Im "Beschreibung" Feld gibt es einen Fall mit Anführungzeichen unten und oben (Deutsch), bei dem beide korrekt angezeigt werden.

Angezeigt wird:
![grafik](https://user-images.githubusercontent.com/82060447/114614284-a2831000-9ca4-11eb-9526-27f737dc36c1.png) 
anstatt:
![grafik](https://user-images.githubusercontent.com/82060447/114614476-d65e3580-9ca4-11eb-8dc2-758f44e2c55c.png)

**Comment by JonaRL** [comment]
Das sollte einfach zu fixen sein. Ich werde es im nächsten Release implementieren.

**Comment by JonaRL** [comment]
Ich habe den Fehler nun behoben, der Fix wird mit dem nächsten offiziellen Release verbreitet.
